### ISSUE TITLE
How to display a local image?

### ISSUE THREAD

**Issue by gitbobobo** [KRTirtho/smtc_windows#7]
I am trying to display a locally cached image on SMTC, but it's not working. I've tried removing `file:///` and replacing `/` with `\`, but neither works. Is this due to Windows security policies preventing access, or is there an issue with the path I've provided?

<img width="357" alt="image" src="https://github.com/KRTirtho/smtc_windows/assets/100769410/c6f9a871-2b2b-4c29-98e1-074978c397bc">

here is the path: `file:///C:/Users/xxx/AppData/Local/Temp/sm_caches/assets/5a161a80-286b-1e6d-bbae-d1bc9e4dd67a.png`

**Comment by Chaphasilor** [comment]
@gitbobobo did you figure it out?

**Comment by Bonfra04** [comment]
@gitbobobo how di did you achieve it?

**Comment by gitbobobo** [comment]
Origin article: https://juejin.cn/post/7363556508603432972

my summay: https://aqzscn.cn/archives/flutter-smtc

you may need translate tool, hope these can help you~

**Comment by Bonfra04** [comment]
I opened a pr to address this issue, it doesn't directly implement local images but being able to pass an array of bytes instead of a path is a good enough workaround, you can use my fork: https://github.com/Bonfra04/smtc_windows/tree/main
